# Generated by Django 4.2.26 on 2025-11-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('installation_date', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид обслуживания')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Вид обслуживания',
                'verbose_name_plural': 'Виды обслуживания',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment', verbose_name='Оборудование')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetype', verbose_name='Вид обслуживания')),
            ],
            options={
                'verbose_name': 'План обслуживания',
                'verbose_name_plural': 'Планы обслуживания',
                'ordering': ['planned_date'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.CreateModel(
            name='MaintenanceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_months', models.IntegerField(verbose_name='Периодичность (месяцев)')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipmenttype', verbose_name='Тип оборудования')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetype', verbose_name='Вид обслуживания')),
            ],
            options={
                'verbose_name': 'Норматив обслуживания',
                'verbose_name_plural': 'Нормативы обслуживания',
                'unique_together': {('equipment_type', 'maintenance_type')},
            },
        ),
    ]
