# Generated by Django 4.2.26 on 2025-12-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenanceplan_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlanExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_extension_date', models.DateField(verbose_name='Дата последнего продления')),
                ('next_extension_date', models.DateField(verbose_name='Дата следующего продления')),
                ('extension_years', models.IntegerField(default=3, verbose_name='Лет на продление')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Продление планов',
                'verbose_name_plural': 'Продления планов',
            },
        ),
    ]
